name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: configure
      run: sudo apt update
      
    - name: configure2
      run: sudo apt install python3-pip
      
    - name: configure3
      run: pip install -r src/requirements.txt
         
            
      
    - name : runner
      run : pytest src/tests

 
